import type { Category, Product, Testimonial } from './types';

export const siteConfig = {
    name: "Afrah Organic Mart",
    phone: "01830989616",
    email: "contact@afrahorganic.com",
    address: "Dhaka, Bangladesh",
    social: {
        facebook: "https://facebook.com",
        instagram: "https://instagram.com",
    },
};

export const categories: Category[] = [
  { id: '1', name: 'Dates', slug: 'dates', image: 'category-dates' },
  { id: '2', name: 'Pure Gur', slug: 'pure-gur', image: 'category-gur' },
  { id: '3', name: 'Chia Seeds', slug: 'chia-seeds', image: 'category-chia' },
  { id: '4', name: 'Shutki', slug: 'shutki', image: 'category-shutki' },
  { id: '5', name: 'Pickles', slug: 'pickles', image: 'category-pickles' },
  { id: '6', name: 'Nuts', slug: 'nuts', image: 'category-nuts' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Ajwa Dates',
    slug: 'premium-ajwa-dates',
    category: 'Dates',
    images: ['product-ajwa', 'product-ajwa-2', 'product-ajwa-3'],
    price: 1200,
    originalPrice: 1500,
    rating: 4.9,
    reviews: 120,
    stock: 50,
    isNew: true,
  },
  {
    id: '2',
    name: 'Medjool Dates (Jumbo)',
    slug: 'medjool-dates-jumbo',
    category: 'Dates',
    images: ['product-medjool'],
    price: 950,
    rating: 4.8,
    reviews: 95,
    stock: 30,
  },
  {
    id: '3',
    name: 'Organic Almonds',
    slug: 'organic-almonds',
    category: 'Nuts',
    images: ['product-almonds'],
    price: 600,
    rating: 4.7,
    reviews: 75,
    stock: 100,
    isNew: true,
  },
  {
    id: '4',
    name: 'Natural Chia Seeds',
    slug: 'natural-chia-seeds',
    category: 'Chia Seeds',
    images: ['product-chia'],
    price: 350,
    rating: 4.9,
    reviews: 210,
    stock: 200,
  },
  {
    id: '5',
    name: 'Safawi Dates',
    slug: 'safawi-dates',
    category: 'Dates',
    images: ['product-safawi'],
    price: 800,
    rating: 4.6,
    reviews: 60,
    stock: 45,
  },
  {
    id: '6',
    name: 'Date Palm Jaggery (Gur)',
    slug: 'date-palm-jaggery-gur',
    category: 'Pure Gur',
    images: ['product-gur'],
    price: 450,
    rating: 4.8,
    reviews: 150,
    stock: 80,
    isNew: true,
  },
  {
    id: '7',
    name: 'Mixed Nuts Deluxe',
    slug: 'mixed-nuts-deluxe',
    category: 'Nuts',
    images: ['product-mixed-nuts'],
    price: 1100,
    originalPrice: 1300,
    rating: 4.9,
    reviews: 88,
    stock: 25,
  },
  {
    id: '8',
    name: 'Spicy Mango Pickle',
    slug: 'spicy-mango-pickle',
    category: 'Pickles',
    images: ['product-pickle'],
    price: 280,
    rating: 4.7,
    reviews: 45,
    stock: 60,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Anika Rahman',
    title: 'Regular Customer',
    quote: 'The quality of dates from Afrah Organic Mart is unparalleled. Always fresh and delicious. My family loves them!',
    avatar: 'avatar-1',
  },
  {
    id: '2',
    name: 'Fazle Rabbi',
    title: 'Health Enthusiast',
    quote: 'I trust Afrah for all my organic needs. Their chia seeds and nuts are top-notch. Highly recommended for a healthy lifestyle.',
    avatar: 'avatar-2',
  },
  {
    id: '3',
    name: 'Sadia Islam',
    title: 'Home Chef',
    quote: 'The pickles and gur have an authentic taste that reminds me of my village. It\'s clear they use high-quality, pure ingredients.',
    avatar: 'avatar-3',
  },
    {
    id: '4',
    name: 'Karim Ahmed',
    title: 'Fitness Coach',
    quote: 'Excellent source of natural energy. The mixed nuts are my go-to snack before workouts. Fast delivery is a huge plus!',
    avatar: 'avatar-4',
  },
];
